name: HACS validate (plugin)

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"   # kør dagligt
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: HACS validation
        uses: hacs/[email protected]
        with:
          category: plugin   # brug "integration" hvis det var en integration
